server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 86400

jwt:
  secret: testtesttesttesttsttesttesttesttest

spring:
  profiles:
    active: local
    group:
      local: local
      dev: dev
      prod: prod
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    org:
      hibernate: info
