server:
  port: 8801

rootPath: /home/kimd0/
rootImagePath: /home/kimd0/image

spring:
  config:
    activate:
      on-profile: dev
  session:
    store-type: redis
  redis:
    host: redis_dev
    port: 6379

database:
  datasource:
    auth:
      url: jdbc:mysql://mysql_dev:3306/auth?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 4
      connection-timeout: 30000
      maxLifetime : 1800000
    slave:
      url: jdbc:mysql://mysql_dev:3306/slave?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 4
      connection-timeout: 30000
      maxLifetime : 1800000