server:
  port: 8801

rootPath: C:\\
rootImagePath: C:\\image

spring:
  config:
    activate:
      on-profile: local
  session:
    store-type: redis
  redis:
    host: 210.123.252.85
    port: 26379

database:
  datasource:
    auth:
      url: jdbc:mysql://210.123.252.85:23306/CAUTH?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 8
      connection-timeout: 30000
      maxLifetime : 1800000
    slave:
      url: jdbc:mysql://210.123.252.85:23306/CSLAVE?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 8
      connection-timeout: 30000
      maxLifetime : 1800000